// Platform-specific constants for Zebra IPTV

export const PLATFORM_DETAILS = [
  {
    id: "apple-tv",
    name: "Apple TV",
    fullName: "Apple TV (tvOS)",
    description:
      "Experience Zebra IPTV on the big screen with our optimized Apple TV app. Enjoy 4K streaming with full remote control support.",
    icon: "mdi:apple",
    available: true,
    featured: true,
    downloadUrl: "/download/appletv",
    appStoreUrl: "https://apps.apple.com/app/zebraiptv",
    requirements: "tvOS 14.0 or later",
    size: "52 MB",
    version: "1.0.0",
    features: [
      "4K HDR Streaming",
      "Siri Remote Support",
      "Picture in Picture",
      "Spatial Audio",
      "Multi-user Profiles",
      "Siri Voice Control",
    ],
    screenshots: [
      "/images/screenshots/appletv-home.jpg",
      "/images/screenshots/appletv-player.jpg",
      "/images/screenshots/appletv-library.jpg",
    ],
    rating: 4.8,
    reviewCount: 1250,
  },
  {
    id: "ios",
    name: "iOS",
    fullName: "iPhone & iPad",
    description:
      "Stream your favorite content on the go with our mobile app. Available for iPhone and iPad with seamless sync.",
    icon: "mdi:apple-ios",
    available: true,
    featured: true,
    downloadUrl: "/download/ios",
    appStoreUrl: "https://apps.apple.com/app/zebraiptv",
    requirements: "iOS 14.0 or later",
    size: "45 MB",
    version: "1.0.0",
    features: [
      "AirPlay Streaming",
      "Picture in Picture",
      "Handoff Support",
      "Widget Support",
      "Offline Downloads",
      "CarPlay Ready",
    ],
    screenshots: [
      "/images/screenshots/ios-home.jpg",
      "/images/screenshots/ios-player.jpg",
      "/images/screenshots/ios-library.jpg",
    ],
    rating: 4.7,
    reviewCount: 850,
  },
  {
    id: "macos",
    name: "macOS",
    fullName: "Mac (macOS)",
    description:
      "Enjoy Zebra IPTV natively on your Mac. Optimized for desktop use and full integration with macOS features.",
    icon: "mdi:apple",
    available: false,
    featured: true,
    downloadUrl: "/download/macos",
    appStoreUrl: "https://apps.apple.com/app/zebraiptv-mac", // placeholder, update when available
    requirements: "macOS 12.0 or later (Apple Silicon recommended)",
    size: "60 MB",
    version: "Coming Soon",
    features: [
      "Native Apple Silicon Support",
      "Universal macOS App",
      "Full Screen & Split View",
      "Keyboard Shortcuts",
      "Continuity & Handoff",
      "Media Keys Control",
    ],
    screenshots: [
      "/images/screenshots/macos-home.jpg",
      "/images/screenshots/macos-player.jpg",
      "/images/screenshots/macos-library.jpg",
    ],
    rating: null,
    reviewCount: null,
  },
  {
    id: "ipad",
    name: "iPadOS",
    fullName: "iPad (iPadOS)",
    description:
      "Tailored for iPad, delivering seamless streaming, multitasking, and Apple Pencil support.",
    icon: "mdi:tablet-ipad",
    available: true,
    featured: true,
    downloadUrl: "/download/ipad",
    appStoreUrl: "https://apps.apple.com/app/zebraiptv",
    requirements: "iPadOS 14.0 or later",
    size: "48 MB",
    version: "1.0.0",
    features: [
      "Split View & Slide Over",
      "Apple Pencil Support",
      "Picture in Picture",
      "Drag & Drop Playlist Import",
      "Keyboard Shortcuts",
      "Seamless Sync Across Devices",
    ],
    screenshots: [
      "/images/screenshots/ipad-home.jpg",
      "/images/screenshots/ipad-player.jpg",
      "/images/screenshots/ipad-library.jpg",
    ],
    rating: 4.8,
    reviewCount: 915,
  },
  {
    id: "android",
    name: "Android",
    fullName: "Android Phones & Tablets",
    description:
      "Get Zebra IPTV on your Android device. Supports phones, tablets, and Android TV boxes.",
    icon: "mdi:android",
    available: true,
    featured: true,
    downloadUrl: "/download/android",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.zebraiptv.app",
    requirements: "Android 6.0 or later",
    size: "38 MB",
    version: "1.0.0",
    features: [
      "Chromecast Support",
      "Android TV Compatible",
      "Split Screen Mode",
      "Background Play",
      "Material Design",
      "Customizable Themes",
    ],
    screenshots: [
      "/images/screenshots/android-home.jpg",
      "/images/screenshots/android-player.jpg",
      "/images/screenshots/android-library.jpg",
    ],
    rating: 4.6,
    reviewCount: 447,
  },
  {
    id: "android-tv",
    name: "Android TV",
    fullName: "Android TV & Google TV",
    description:
      "Optimized for your Android TV or Google TV device with a beautiful 10-foot interface.",
    icon: "mdi:television",
    available: true,
    featured: false,
    downloadUrl: "/download/android-tv",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.zebraiptv.tv",
    requirements: "Android TV 7.0 or later",
    size: "42 MB",
    version: "1.0.0",
    features: [
      "Voice Search",
      "4K Support",
      "Leanback Interface",
      "Remote Control",
      "Recommendations",
      "Live Channels Integration",
    ],
    screenshots: [
      "/images/screenshots/androidtv-home.jpg",
      "/images/screenshots/androidtv-player.jpg",
    ],
    rating: 4.5,
    reviewCount: 320,
  },
  {
    id: "windows",
    name: "Windows",
    fullName: "Windows PC & Tablet",
    description:
      "Coming soon: Seamless IPTV experience on Windows. Modern, fast, and built for productivity, mouse, touch, and keyboard.",
    icon: "mdi:microsoft-windows",
    available: false,
    featured: false,
    downloadUrl: "#",
    microsoftStoreUrl: "https://www.microsoft.com/store/apps",
    requirements: "Windows 10 version 1809 or later",
    size: "TBD",
    version: "Coming Soon",
    features: [
      "Native Windows App",
      "Touch & Mouse Friendly",
      "Window Snap & Multi-tasking",
      "Live Tile Support",
      "Dark Mode",
      "Easy Playlist Import",
    ],
    screenshots: [],
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "webos-tv",
    name: "webOS TV",
    fullName: "LG webOS Smart TV",
    description:
      "Coming soon: Enjoy Zebra on your LG webOS Smart TV with a native, streamlined app designed for large screens.",
    icon: "mdi:television-classic",
    available: false,
    featured: false,
    downloadUrl: "#",
    lgStoreUrl: "https://www.lg.com/us/support/answers/tv2021/apps-on-lg-tv",
    requirements: "LG webOS 4.0 or later",
    size: "TBD",
    version: "Coming Soon",
    features: [
      "Voice Search with Magic Remote",
      "Ultra HD / 4K Ready",
      "Big Screen Leanback UI",
      "Channel List & EPG",
      "Favorites & Custom Playlists",
      "Native webOS Experience",
    ],
    screenshots: [],
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "tizen-tv",
    name: "Tizen TV",
    fullName: "Samsung Tizen Smart TV",
    description:
      "Coming soon: Enjoy Zebra on your Samsung Tizen Smart TV with a polished, easy-to-use interface built for the big screen.",
    icon: "mdi:television-ambient-light",
    available: false,
    featured: false,
    downloadUrl: "#",
    samsungStoreUrl: "https://www.samsung.com/us/support/answer/ANS00060173/",
    requirements: "Samsung Tizen OS 5.0 or later",
    size: "TBD",
    version: "Coming Soon",
    features: [
      "Universal Search",
      "4K Ultra HD Support",
      "Remote-Friendly UI",
      "Channel List & EPG",
      "Favorites & Custom Playlists",
      "Native Tizen Experience",
    ],
    screenshots: [],
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "fire-tv",
    name: "Fire TV",
    fullName: "Amazon Fire TV",
    description:
      "Watch on your Fire TV Stick or Fire TV Cube with Alexa voice control support.",
    icon: "mdi:amazon",
    available: false,
    featured: false,
    downloadUrl: "#",
    appStoreUrl: "https://www.amazon.com/dp/",
    requirements: "Fire OS 6.0 or later",
    size: "40 MB",
    version: "Coming Soon",
    features: [
      "Alexa Voice Control",
      "4K Ultra HD",
      "Fire TV Remote",
      "Prime Integration",
      "X-Ray Features",
    ],
    screenshots: [],
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "web",
    name: "Web",
    fullName: "Web Browser",
    description:
      "Coming soon: Stream directly in your web browser without any downloads required.",
    icon: "mdi:web",
    available: false,
    featured: false,
    downloadUrl: "#",
    requirements: "Modern web browser (Chrome, Firefox, Safari, Edge)",
    size: "N/A",
    version: "Coming Soon",
    features: [
      "No Installation Required",
      "Cross-Platform",
      "Cloud Sync",
      "Responsive Design",
      "PWA Support",
    ],
    screenshots: [],
    rating: 0,
    reviewCount: 0,
  },
] as const;

export const PLATFORM_CATEGORIES = {
  mobile: ["ios", "android"],
  web: ["web"],
  desktop: ["macos", "windows"],
  tv: ["apple-tv", "android-tv", "fire-tv", "webos-tv", "tizen-tv"],
  smarttv: ["webos-tv", "tizen-tv"],
  tablet: ["ipad"],
  phone: ["ios", "android"],
  computer: ["macos", "windows"],
  other: ["web"],
} as const;

export const DOWNLOAD_BADGES = {
  appStore: {
    src: "/images/badges/app-store.svg",
    alt: "Download on the App Store",
    width: 135,
    height: 40,
  },
  googlePlay: {
    src: "/images/badges/google-play.svg",
    alt: "Get it on Google Play",
    width: 135,
    height: 40,
  },
  amazonAppstore: {
    src: "/images/badges/amazon-appstore.svg",
    alt: "Available at Amazon Appstore",
    width: 135,
    height: 40,
  },
} as const;
