// Platform-specific constants for Zebra IPTV

export const PLATFORM_DETAILS = [
  {
    id: "apple-tv",
    name: "Apple TV",
    fullName: "Apple TV (tvOS)",
    description: "Experience Zebra IPTV on the big screen with our optimized Apple TV app. Enjoy 4K streaming with full remote control support.",
    icon: "mdi:apple",
    available: true,
    featured: true,
    downloadUrl: "/download/appletv",
    appStoreUrl: "https://apps.apple.com/app/zebraiptv",
    requirements: "tvOS 14.0 or later",
    size: "52 MB",
    version: "1.0.0",
    features: [
      "4K HDR Streaming",
      "Siri Remote Support",
      "Picture in Picture",
      "Spatial Audio",
      "Multi-user Profiles",
      "Siri Voice Control",
    ],
    screenshots: [
      "/images/screenshots/appletv-home.jpg",
      "/images/screenshots/appletv-player.jpg",
      "/images/screenshots/appletv-library.jpg",
    ],
    rating: 4.8,
    reviewCount: 1250,
  },
  {
    id: "ios",
    name: "iOS",
    fullName: "iPhone & iPad",
    description: "Stream your favorite content on the go with our mobile app. Available for iPhone and iPad with seamless sync.",
    icon: "mdi:apple-ios",
    available: true,
    featured: true,
    downloadUrl: "/download/ios",
    appStoreUrl: "https://apps.apple.com/app/zebraiptv",
    requirements: "iOS 14.0 or later",
    size: "45 MB",
    version: "1.0.0",
    features: [
      "AirPlay Streaming",
      "Picture in Picture",
      "Handoff Support",
      "Widget Support",
      "Offline Downloads",
      "CarPlay Ready",
    ],
    screenshots: [
      "/images/screenshots/ios-home.jpg",
      "/images/screenshots/ios-player.jpg",
      "/images/screenshots/ios-library.jpg",
    ],
    rating: 4.7,
    reviewCount: 850,
  },
  {
    id: "android",
    name: "Android",
    fullName: "Android Phones & Tablets",
    description: "Get Zebra IPTV on your Android device. Supports phones, tablets, and Android TV boxes.",
    icon: "mdi:android",
    available: true,
    featured: true,
    downloadUrl: "/download/android",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.zebraiptv.app",
    requirements: "Android 6.0 or later",
    size: "38 MB",
    version: "1.0.0",
    features: [
      "Chromecast Support",
      "Android TV Compatible",
      "Split Screen Mode",
      "Background Play",
      "Material Design",
      "Customizable Themes",
    ],
    screenshots: [
      "/images/screenshots/android-home.jpg",
      "/images/screenshots/android-player.jpg",
      "/images/screenshots/android-library.jpg",
    ],
    rating: 4.6,
    reviewCount: 447,
  },
  {
    id: "android-tv",
    name: "Android TV",
    fullName: "Android TV & Google TV",
    description: "Optimized for your Android TV or Google TV device with a beautiful 10-foot interface.",
    icon: "mdi:television",
    available: true,
    featured: false,
    downloadUrl: "/download/android-tv",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.zebraiptv.tv",
    requirements: "Android TV 7.0 or later",
    size: "42 MB",
    version: "1.0.0",
    features: [
      "Voice Search",
      "4K Support",
      "Leanback Interface",
      "Remote Control",
      "Recommendations",
      "Live Channels Integration",
    ],
    screenshots: [
      "/images/screenshots/androidtv-home.jpg",
      "/images/screenshots/androidtv-player.jpg",
    ],
    rating: 4.5,
    reviewCount: 320,
  },
  {
    id: "fire-tv",
    name: "Fire TV",
    fullName: "Amazon Fire TV",
    description: "Watch on your Fire TV Stick or Fire TV Cube with Alexa voice control support.",
    icon: "mdi:amazon",
    available: false,
    featured: false,
    downloadUrl: "#",
    appStoreUrl: "https://www.amazon.com/dp/",
    requirements: "Fire OS 6.0 or later",
    size: "40 MB",
    version: "Coming Soon",
    features: [
      "Alexa Voice Control",
      "4K Ultra HD",
      "Fire TV Remote",
      "Prime Integration",
      "X-Ray Features",
    ],
    screenshots: [],
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "web",
    name: "Web",
    fullName: "Web Browser",
    description: "Coming soon: Stream directly in your web browser without any downloads required.",
    icon: "mdi:web",
    available: false,
    featured: false,
    downloadUrl: "#",
    requirements: "Modern web browser (Chrome, Firefox, Safari, Edge)",
    size: "N/A",
    version: "Coming Soon",
    features: [
      "No Installation Required",
      "Cross-Platform",
      "Cloud Sync",
      "Responsive Design",
      "PWA Support",
    ],
    screenshots: [],
    rating: 0,
    reviewCount: 0,
  },
] as const;

export const PLATFORM_CATEGORIES = {
  mobile: ["ios", "android"],
  tv: ["apple-tv", "android-tv", "fire-tv"],
  web: ["web"],
} as const;

export const DOWNLOAD_BADGES = {
  appStore: {
    src: "/images/badges/app-store.svg",
    alt: "Download on the App Store",
    width: 135,
    height: 40,
  },
  googlePlay: {
    src: "/images/badges/google-play.svg",
    alt: "Get it on Google Play",
    width: 135,
    height: 40,
  },
  amazonAppstore: {
    src: "/images/badges/amazon-appstore.svg",
    alt: "Available at Amazon Appstore",
    width: 135,
    height: 40,
  },
} as const;

